### ISSUE TITLE
https://stackoverflow.com/questions/53693645

### ISSUE THREAD

**Issue by fmbenhassine** [chichasonu/Spring-Multi-Ds-Batch#1]
Hi,

I was not able to run your code because I don't have a SqlServer, but I checked your configuration and noted a couple of issues:

* Providing a custom transaction manager by overriding `DefaultBatchConfigurer#getTransactionManager` works only with Spring Batch v4.1+ [as said in comments](
https://stackoverflow.com/questions/53693645/spring-batch-multiple-datasource-session-entitymanager-closed?noredirect=1#comment94257974_53693645). But here you are using Spring Batch v4.0.1. You need to use Spring Boot v2.1 to have Spring Batch 4.1
* I would use the `JpaItemWriter` instead of `DatwWriter`. The `JpaItemWriter` correctly [creates a transactional entity manager](https://github.com/spring-projects/spring-batch/blob/master/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/database/JpaItemWriter.java#L79) and flushes entities after writing them, while `DatwWriter` does not do that.
* You secondary datasource should scan `sqlserver` entities [here](https://github.com/chichasonu/Spring-Multi-Ds-Batch/blob/master/src/main/java/com/spring/batch/example/config/SecondaryDataSourceConfiguration.java#L49) and not `mysql` ones.
* It is usually a [good practice](https://github.com/spring-projects/spring-batch/blob/master/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/database/JdbcPagingItemReader.java#L61) to make the chunk size = page size. In your case, they are 100 and 1000 respectively. Moreover, you set the max item count to 1000, which means there will be a single query to the db. Is that intended?
* In `application.properties` I would remove the prefix `primary.` as it is enough to have `datasource.mysql` and `datasource.sqlServer` to distinguish datasources.

You can start by addressing those issues and your problem should be fixed.

**Comment by chichasonu** [comment]
Thanks a lot for your Time and Effort.
I have made the changes and its working like charm

**Comment by fmbenhassine** [comment]
Great! Glad it helped.
